### ISSUE TITLE
Where do I put the WZ files?

### ISSUE THREAD

**Issue by FlafyDev** [crrio/maplestory.io#1]
Hi, in order to use this the website would need to get data from WZ files, right?
So where do I put the WZ files then?

Or maybe I'm doing something wrong?

**Comment by corsair** [comment]
Hello @FlafyDev,

The code contained in this repository, unfortunately, does not function properly as it was initially coded to only support a specific environment. It should be treated AS IS.

I'll add a README to provide this information. Sorry for the trouble and best of luck with your development. If you have any further questions, please feel free to let me know at tyler@crr.io.
