### ISSUE TITLE
Organize API Endpoints by Category

### ISSUE THREAD

**Issue by crr** [crrio/maplestory.io#11]
## Description

All API Endpoints should be organized by their related category to allow for easier navigating by developers, as well as renamed to make it more efficient.

### Server
**– /api/server/list**
Gets statistical data of all servers.

**– /api/server/:serverId/**
Gets statistical data of a server.

**– /api/server/:serverId/itemCount**
Gets a count of items in the server.

**– /api/server/:serverId/icon**
Gets the icon of a server.

**– /api/server/:serverId/market**
Gets a list of rooms with the shops and items in a server.

**– /api/server/:serverId/market/legacy**
Gets all of the items in the server.

**– /api/server/:serverId/market/:roomId**
Gets a list of shops and items in a specific room on a specific server.

**– /api/server/:serverId/market/:roomId/items**
Gets a list of items in a specific room on a specific server.

### Character
**– /api/character/:characterName**
Gets the ranking information of a character.

**– /api/character/:characterName/avatar**
Gets the avatar of a character

**– /api/character/:characterName/fame**
Gets the fame of a character

### Item
**– /api/item/:itemId**
Gets the information of an item.

**– /api/item/:itemId/icon**
Gets the inventory icon of an item.

**– /api/item/:itemId/iconRaw**
Gets the raw icon of an item.

**– /api/item/list**
A complete list of all items in MapleStory.

**Comment by crr** [comment]
Updated issue with suggested API endpoints and descriptions.

**Comment by Inumedia** [comment]
Closes 4c8579b
