### ISSUE TITLE
Item Information

### ISSUE THREAD

**Issue by crr** [crrio/maplestory.io#14]
## Description
We want to provide detailed information about MapleStory's items, and allow for other services to take advantage of updated and current information.

### Additional Notes
An API for both individual items (/api/maplestory/item/:itemId) and requesting a complete item list (/api/maplestory/item/all or /api/maplestory/itemlist)

Please note, we should remove all "hair and eye" items from the list.

**Comment by crr** [comment]
The API for individual items should also contain some information related to the Free Market, such as averagePrice.

**Comment by crr** [comment]
A complete item list API was added by @inumedia in 278b9cc.

Awaiting individual item API, and either filtering or removal of hair/eye items.

**Comment by Inumedia** [comment]
Fixed in 4c8579b71
