### ISSUE TITLE
Character info API returns strings for integer fields

### ISSUE THREAD

**Issue by diamondo25** [crrio/maplestory.io#16]
It's unclear why 'EXP' and 'Ranking' are both strings.
```
{
  "name": "SomePerson123",
  "job": "Magician",
  "ranking": "1",
  "world": "Khaini",
  "level": 255,
  "exp": "4339186",
  "rankMovement": 1,
  "rankDirection": "up",
  "avatar": "/api/character/SomePerson123/avatar",
  "got": "2016-10-05T04:48:21.537Z",
  "avatarData": "data:image/png;base64,"
}
```

**Comment by Inumedia** [comment]
Those are strings due to JavaScript not having native longs, if I recall correctly.

**Comment by diamondo25** [comment]
Up to 9,999,999,999,999,998 is correct. +1 will go to 10000000000000000.

```
$ JSON.stringify({hurr: 9999999999999998})
"{"hurr":9999999999999998}"
```

**Comment by diamondo25** [comment]
And max EXP gained in a month is 28,646,624,402 , so there's enough space

**Comment by diamondo25** [comment]
Lowest rank for GMS NA is 27,154,025 (last character rank is 25,934,792, with duplicates)

http://maplestory.nexon.net/rankings/overall-ranking/legendary?pageIndex=27154025#ranking

**Comment by Inumedia** [comment]
Yeah, my biggest concern was future proofing, but I can switch it over to numbers instead of strings.
