### ISSUE TITLE
[Item API] Add proper CORS to item icon APIs.

### ISSUE THREAD

**Issue by crr** [crrio/maplestory.io#23]
### Description
The item icon APIs (icon and iconRaw) do not have proper CORS to allow external locations to access them without resulting in errors or warnings.

**Comment by Inumedia** [comment]
![image](https://cloud.githubusercontent.com/assets/856822/21791550/8513acb8-d6b1-11e6-9549-39d5c3bf39d9.png)

It looks like there are proper CORS on the item icon APIs 😃

**Comment by crr** [comment]
Applying wontfix to this as it was a bug un-related to this repository.
