### ISSUE TITLE
[Server API]:worldName/icon

### ISSUE THREAD

**Issue by holthelper** [crrio/maplestory.io#24]
returns json instead of image.

**Comment by crr** [comment]
Nice catch. We had this issue prior with other icons, although if I recall it was unrelated to the source itself and was a fix on either the server or database.

Will assign to @Inumedia to confirm.

**Comment by Inumedia** [comment]
Issue was caused by the switch to calling `success` instead of `send`, `success` expects a JSON response, which an icon is not. 😛

Issue is resolved in b761420651cf847e7b1cdbc04b4e96c29a15488e.
